#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.org4.example.com:
    container_name: ca_peerOrg4
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    ports:
      - 10054:7054

  couchdb04:
    container_name: couchdb04
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=peer0org4
      - COUCHDB_PASSWORD=nothingcomplex@123
    ports:
      - "10984:5984"

  couchdb14:
    container_name: couchdb14
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=peer1org4
      - COUCHDB_PASSWORD=nothingcomplex@123
    ports:
      - "10985:5984"
  
  couchdb24:
    container_name: couchdb24
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=peer2org4
      - COUCHDB_PASSWORD=nothingcomplex@123
    ports:
      - "10986:5984"

  peer0.org4.example.com:
    container_name: peer0.org4.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_ADDRESS=peer0.org4.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb04:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0org4
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=nothingcomplex@123
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/:/etc/hyperledger/crypto/peer
    depends_on:     
      - couchdb04

  peer1.org4.example.com:
    container_name: peer1.org4.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_ADDRESS=peer1.org4.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb14:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1org4
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=nothingcomplex@123
    ports:
      - 10151:7051
      - 10153:7053
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/peers/peer1.org4.example.com/:/etc/hyperledger/crypto/peer
    depends_on:     
      - couchdb14

  peer2.org4.example.com:
    container_name: peer2.org4.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_ADDRESS=peer2.org4.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb24:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer2org4
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=nothingcomplex@123
    ports:
      - 10251:7051
      - 10253:7053
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/peers/peer2.org4.example.com/:/etc/hyperledger/crypto/peer
    depends_on:     
      - couchdb24

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org4.example.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 600000000000000000'
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:    
      - peer0.org4.example.com
      
      